name = "WoCDiversity"
uuid = "cf69b460-55de-4cea-82ae-6d1bb98dde44"
authors = ["José Bayoán Santiago Calderón <jbs3hp@virginia.edu>"]
version = "0.1.0"

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Mongoc = "4fe8b98c-fc19-5c23-8ec2-168ff83495f2"
